default_stages: [pre-commit, pre-push, commit-msg]
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: ['--fix=auto']

# Check commit message
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
  hooks:
    - id: commitizen

# Lint GitHub Actions
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
    - id: actionlint

# Automatic formatting
hooks:
  - id: rustfmt
    name: rustfmt
    entry: cargo fmt
    require_serial: true
    pass_filenames: false
    language: system
